### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rabinneslo** [DerwenAI/pytextrank#19]
Hi,

I'm getting the following error when trying to run pytextrank with my own data. Is there a way to fix this?

app_1    | Traceback (most recent call last):
app_1    |   File "index.py", line 26, in <module>
app_1    |     for rl in pytextrank.normalize_key_phrases(path_stage1, ranks):
app_1    |   File "/usr/local/lib/python3.6/site-packages/pytextrank/pytextrank.py", line 581, in normalize_key_phrases
app_1    |     for rl in collect_entities(sent, ranks, stopwords, spacy_nlp):
app_1    |   File "/usr/local/lib/python3.6/site-packages/pytextrank/pytextrank.py", line 485, in collect_entities
app_1    |     w_ranks, w_ids = find_entity(sent, ranks, ent.text.split(" "), 0)
app_1    |   File "/usr/local/lib/python3.6/site-packages/pytextrank/pytextrank.py", line 454, in find_entity
app_1    |     return find_entity(sent, ranks, ent, i + 1)
app_1    |   File "/usr/local/lib/python3.6/site-packages/pytextrank/pytextrank.py", line 454, in find_entity
app_1    |     return find_entity(sent, ranks, ent, i + 1)
app_1    |   File "/usr/local/lib/python3.6/site-packages/pytextrank/pytextrank.py", line 454, in find_entity
app_1    |     return find_entity(sent, ranks, ent, i + 1)
app_1    |   [Previous line repeated 137 more times]
app_1    |   File "/usr/local/lib/python3.6/site-packages/pytextrank/pytextrank.py", line 451, in find_entity
app_1    |     w = sent[i + j]
app_1    | IndexError: list index out of range

**Comment by chuckhelios** [comment]
Got same error

**Comment by chuckhelios** [comment]
file to replicate the error:
{"id": "17172.docx.json", "text": "\r\nTransitional Aid to Families with Dependent Children (TAFDC)  \r\nConsolidated Report\r\n\t\r\nJanuary, 2017\r\n\r\nReport on Transitional Aid to Families with Dependent Children (TAFDC)\r\nConsolidated Report\r\nJanuary 2017\r\nOverview\r\nIn response to the following legislatives reporting requirements, the Department of Transitional Assistance (DTA) is pleased to provide this comprehensive report on the current status of the TAFDC program including work program requirements, an update on the implementation of Pathways to Self Sufficiency Initiative and the role of the Self Sufficiency Specialist. \r\nLegislative Reporting Requirements \r\nChapter 18 Section 2 of the Massachusetts General Laws requires the Department of Transitional Assistance (DTA) to annually report regarding the Transitional Aid to Families with Dependent Children work requirement.   \r\nChapter 118 Section 3C of the Massachusetts General Laws requires the Department of Transitional Assistance (DTA) to annually report on the Pathways to Self-Sufficiency Program.  \r\nChapter 18 Section 5 of the Massachusetts General Laws requires the Department of Transitional Assistance (DTA) to annually report on the specialists positions established by the commissioner, known as Self-Sufficiency Specialist.  \r\nBackground \r\nDTA\u2019s mission is to assist and empower low-income individuals and families to meet their basic needs, improve their quality of life, and achieve long-term economic self-sufficiency. DTA offers a comprehensive system of programs and supports to help individuals and families achieve greater economic self-sufficiency, including food and nutritional assistance, cash assistance, and employment supports. DTA serves one out of every eight people in the Commonwealth including working families, children, elders, and people with disabilities. \r\nMassachusetts has one of the strongest economies in the country. Despite its educated workforce, high median wage and low unemployment rate, almost 40% of Massachusetts\u2019 children live in low-income families with a parent that works full time. Children of color are especially likely to live in low-income families. \r\nResearch demonstrates a lack of family income, especially during a child\u2019s early years, has immediate and life-long consequences. Children living in poverty are less likely to enter school ready to learn, perform at grade-level, graduate from high school or go to college. As adults they are less likely to participate in the workforce and to achieve economic security for themselves and their children. \r\nOver the past two years, DTA has focused its efforts on implementing the 2014 Welfare Reform Law and placing a renewed emphasis on our employment program to focus on comprehensive and innovative ways to assist our clients moving towards financial independence and economic self-sufficiency. While it is premature to determine if the Pathway to Self-Sufficiency (PSS) program is generating the desired outcomes in only its sixth month of operation, DTA\u2019s front-line staff expresses pride in this shift back to more meaningful client engagement. DTA is focused on reinforcing this program through enhanced avenues of staff input, comprehensive continuous improvement measures, and a review of PSS-related client outcomes. \r\nDTA is also an essential partner in the state\u2019s efforts to implement the Workforce Innovation and Opportunity Act (WIOA), which was signed into law by President Obama on July 22, 2014. WIOA seeks to integrate the states\u2019 workforce systems to better serve employers and jobseekers. WIOA reauthorized the nation\u2019s employment, training, adult education and vocational rehabilitation programs for the first time in 16 years. The new law is substantially different from its predecessor, the Workforce Investment Act (WIA), in its emphasis on targeting low-income adults and youth with limited training and skills to help them overcome barriers to economic success, as well as individuals with disabilities. \r\nSince the passage of WIOA, DTA has been working closely with EOLWD to plan for implementation of a new, closely integrated system of workforce development for DTA clients and others with significant barriers to work. \r\nThe aim of this collaboration is to:\r\ndevelop a meaningful pathway to work and economic self-sufficiency for low-income, disabled and chronically un/underemployed individuals/families; and \r\nensure DTA individuals and families with significant barriers can access the workforce system with the support needed to attain and sustain employment.\r\nWe look forward to reporting on the progress of our Pathways to Self Sufficiency Program and our collaborative work with partners in workforce development to secure better economic futures for DTA clients and their children. \r\nTransitional Aid to Families with Dependent Children (TAFDC)\r\nTAFDC is a state and federally-funded program that provides cash assistance to families with children, and pregnant women, with little or no assets or income. TAFDC is operated under the federal Temporary Assistance for Needy Families (TANF) block grant. Participants receive child care and transportation support associated with job assistance, and can access a number of supportive referrals. As a part of TAFDC, participants may be required to perform a work-related activity as a condition of eligibility. \r\nHowever, many if not all individuals receiving TAFDC, face challenges to employment and long term economic self-sufficiency. These challenges include: need for job training, a high school diploma/equivalency, English as a Second Language services, child care, transportation or mental health services. \r\nTransitional Aid to Families with Dependent Children Caseload \r\nOf the total TAFDC caseload of 31,730 Caseload as of November 2016\r\n, those clients who have a work program requirement total: 6,981. That leaves the remainder of the caseload (24,749 clients) exempt from the work program requirement. Since June 27, 2016, DTA has been tracking and collecting data through our Pathways to Self-Sufficiency (PSS) assessment to better understand the challenges and strengths of our clients. The availability of low-cost transportation as well as safe and affordable child care are the two main challenges facing TAFDC recipients who are pursuing employment opportunities. Beyond these well documented barriers, over 1,500 clients who are work program required report that they are in need of additional education, training or other barrier-removal services to help them gain employment. On average, DTA clients remain on TAFDC for 36 months.\r\nGrant levels have remained unchanged since 2000:\r\nExempt Assistance Units receive monthly:\r\nAssistance\t\tA.\tPayment Standard\t\t\tB.\tPayment Standard\r\nUnit Size \t\t\tNo Rent Allowance\t\t\t\tWith Rent Allowance\r\n     1\t\t\t\t\t$388.00\t\t\t\t\t$428.00\r\n     2\t\t\t\t\t  491.00\t\t\t\t\t  531.00\r\n     3\t\t\t\t\t  593.00\t\t\t\t\t  633.00\r\n     4\t\t\t\t\t  691.00\t\t\t\t\t  731.00\r\n     5\t\t\t\t\t  792.00\t\t\t\t\t  832.00\r\n     6\t\t\t\t              896.00\t\t\t\t              936.00\r\n     7\t\t\t\t              997.00\t\t\t\t           1,037.00\r\n     8\t\t\t\t           1,097.00\t\t\t\t           1,137.00\r\n     9\t\t\t\t           1,197.00\t\t\t\t           1,237.00\r\n     10\t\t\t\t           1,298.00\t\t\t\t           1,338.00\r\nIncremental\t\t\t\t  105.00\t\t\t\t\t  105.00\r\nNonexempt Assistance Units receive monthly:\r\nAssistance\t\tA.\tPayment Standard\t\t\tB.\tPayment Standard\r\nUnit Size \t\t\tNo Rent Allowance\t\t\t\tWith Rent Allowance\r\n     1\t\t\t\t\t$378.00\t\t\t\t\t$418.00\r\n     2\t\t\t\t\t  478.00\t\t\t\t\t  518.00\r\nNonexempt Assistance Units receive monthly(continued):\r\nAssistance\t\tA.\tPayment Standard\t\t\tB.\tPayment Standard\r\nUnit Size \t\t\tNo Rent Allowance\t\t\t\tWith Rent Allowance\r\n    \r\n     3\t\t\t\t\t  578.00\t\t\t\t\t  618.00\r\n     4\t\t\t\t\t  673.00\t\t\t\t\t  713.00\r\n     5\t\t\t\t\t  772.00\t\t\t\t\t  812.00\r\n     6\t\t\t\t              872.00\t\t\t\t              912.00\r\n     7\t\t\t\t              971.00\t\t\t\t           1,011.00\r\n     8\t\t\t\t           1,067.00\t\t\t\t           1,107.00\r\n     9\t\t\t\t           1,165.00\t\t\t\t           1,205.00\r\n     10\t\t\t\t           1,263.00\t\t\t\t           1,303.00\r\nIncremental\t\t\t\t  103.00\t\t\t\t\t  103.00\r\nWork Program Requirement Exemptions\r\nThere are a number of reasons for an individual having an exemption from a work program requirement. \r\nExemption reasons include: \r\ndisabled parents; \r\nparents caring for a disabled child or spouse;\r\nparents whose youngest eligible child is less than two or who have any child who is less than three months; \r\nwomen in their  33rd week of pregnancy and those in their third trimester of pregnancy who have a verified medical condition that prevents them from working; \r\nteen parents who are attending school full time; \r\npersons over age sixty-six; and\r\ncaretaker relatives.\r\nExtensions to Time-Limited Benefits\r\nTAFDC benefits are limited to 24-months within a 60-month period for nonexempt households. Recipients may request an extension of benefits when they are nearing the end of their time limit. Extensions are approved for not more than three months at a time; if additional time is requested, the new extension request will be evaluated based on participation in activities approved in the previous extension.\r\nExtensions are requested for a number of reasons, including:\r\nNot yet found employment;\r\nWages are too low; and\r\nCompleting an education/training program already enrolled in prior to requesting the extension.\r\nIn calendar year 2016, DTA received 1122 extension requests, and approved 213 extensions.\r\nPathways to Self Sufficiency\r\nDTA believes that all clients, both those who are subject to time-limited benefits and those who are not, can be assisted in moving to a better economic position and improved quality of life. To that end, DTA created Pathways to Self-Sufficiency (PSS). The goal of PSS is positive client engagement and targeted supports that lead to employment, career pathways and long term economic self-sufficiency.\r\nAs part of PSS, DTA established an individualized employment development plan for all participating clients to document the progress being made towards the stated goal. The steps towards that goal will be individualized based on the needs of the particular client. PSS has at its core that TAFDC is a transitional benefit and emphasizes the importance of working to secure economic self-sufficiency, the supports available and the benefits of not needing public assistance.\r\nImplementation\r\nDTA developed an assessment tool for case managers to utilize when engaging with clients about their self-identified strengths and challenges in reaching economic self-sufficiency. The Bureau of Program Integrity (BPI) facilitated a meeting with New Hampshire\u2019s TANF Director and Career Center Director to discuss and review their assessment model. DTA incorporated into our Pathways assessment those questions that were not already asked in our application that were germane to helping our clients reach economic self-sufficiency. Prior to the workflow being designed, the assessment was tested in a few local DTA offices. Feedback was incorporated to inform the final design of the workflow.\r\nStaff from DTA\u2019s Central Office hosted a presentation for all cash staff regarding the changes that would be instituted with Pathways implementation on June 27. Following this presentation, senior level staff visited all 22 local offices and met with TAFDC case managers to discuss how Pathways would focus their jobs on assisting clients to reach economic self-sufficiency. These sessions provided an opportunity for case managers to ask questions about the assessment and offer suggestions to fine tune the workflow.\r\nFinally, training sessions were given at DTA\u2019s annual Training Conference held in May as well as webinars developed through DTA\u2019s Training Division. These Webinars (provided in June and available on line for re-viewing) focused on time-management, motivational interviewing techniques, managing difficult conversations and Pathways to Self-Sufficiency BEACON DTA\u2019s data management information and eligibility information system \r\n workflows.\r\nProgress\r\nThe PSS Assessment was launched on June 27, 2016. The cost of implementing the components of PSS was $1,450,456.  It cost DTA on average $3,290 per participant for the 441 available slots. The 441 PSS slots served 6.3% of the 6,981 work program required clients. From those 441 slots, DTA had a 62.5% job placement rate and from that, an 87.2% job retention rate.\r\nThe following components were implemented for Pathways to Self-Sufficiency in light of available resources and appropriations:\r\nCompetitive Integrated Employment Services (CIES) Model II;\r\nCIES Model III;\r\nPre-Benefit Job Search; and \r\nMandatory Orientation. \r\nThe top five reasons clients reported they were unsuccessful in obtaining gainful employment within the 12 months prior to applying for benefits were as follows:\r\n \r\nLack of Skills and training;\r\nLack of work experience; \r\nLimited literacy/math skills;\r\nChild care; and\r\nTransportation.\r\nSelf-Sufficiency Specialists\r\nSelf Sufficiency Specialists (SSS) began their new role at the Department of Transitional Assistance (DTA) in December 2015. In preparation to launch this new role, a detailed job description was developed, training was developed and conducted, and policy documentation about the new role and who it would serve was issued. \r\nBetween April and June 2016, DTA conducted an assessment of how the role was functioning and identified ways to strengthen and clarify the SSS role. While many positive findings resulted from this assessment, there remained issues regarding legislatively mandated caseload caps for these workers. This assessment also concluded limiting the agency\u2019s ability to best utilize resources as policy and circumstance demand would not serve our clients well. \r\nThe rollout of Pathways to Self Sufficiency made it clear that this caseload cap had an adverse impact on DTA\u2019s ability to manage resources and move all clients toward self-sufficiency. DTA recommends that all Case Managers gain the skills and are allowed the time to engage with clients with barriers to employment. Limiting some caseworker\u2019s caseloads results in increases to other caseworker\u2019s caseloads. Ensuring all caseworkers have manageable caseloads is critical, and DTA needs the discretion to make the appropriate decisions regarding what a manageable caseload means. \r\nAs a result, the following recommendations were developed and implemented:\r\nSSS provide intensive case management and support to all teen parents who are heads of household, whether parenting or pregnant.\r\nOther clients who may receive the assistance of an SSS include:\r\nyoung parents (pregnant and/or parenting heads of household under the age of 24); \r\nresidents of emergency assistance shelter, Hotel/Motel, Congregate Shelter, Scattered Site Shelter or Domestic Violence Shelter.\r\nIn limited circumstances, and as determined by a DTA manager, SSSs may also assist other clients who have been identified as having significant challenges in moving towards self-sufficiency. \r\nEach TAO has at least one SSS, with a caseload limited to 60 active clients per specialist. Due to caseload limits, assignment of an SSS will be based on availability. \r\nEffective September 2016, surplus SSSs were reassigned to the cash caseload in order to bring overall caseloads down.\r\nAdditionally, with Pathways now in place, DTA will be able to utilize data to evolve the function of SSS to best serve our clients.\r\nManagers and those serving in the SSS capacity were notified in July of the planned changes with implementation going into effect in early September 2016. In late August, revisions were made to the BEACON Online Guide to reflect the change/clarification in the role, which were published in anticipation of the implementation. \r\nThis shift in focus was in conjunction with establishing specialized EAEDC workers in spring 2016. This established staff dedicated to either an EAEDC caseload or TAFDC caseload where appropriate. The objective of this change was to lower the average caseload for TAFDC caseworkers so they would have more time to focus on moving clients toward self-sufficiency. This was realized, and currently the average TAFDC caseload is approximately 140 clients, a drop from the previous median which approached 200 cases per caseworker. Allowing TAFDC caseworkers more time to engage with clients assists DTA in breaking down barriers and helping clients obtain employment and begin on a path to self-sufficiency. \r\nConclusion\r\nDTA remains committed to its mission of assisting and empowering low-income individuals and families to meet their basic needs, improve their quality of life, and achieve long-term economic self-sufficiency. With Pathways to Self-Sufficiency and Self Sufficiency Specialists, DTA is well positioned to assist all clients in finding a route out of poverty.\r\n2\r\n"}

**Comment by leajaentgen** [comment]
I have the same issue. Does someone know why this is happening and/or has a temporary fix?

**Comment by tsaltena** [comment]
This might be related to issue #9, for me a temp fix is to just always return None, None by adding this directly after 446:

`    return None, None`

**Comment by ceteri** [comment]
Check the [v2.0.0](https://github.com/DerwenAI/pytextrank/releases/tag/v2.0.0) release for updates that should resolve these issues.
