### ISSUE TITLE
Scipy missing from dependencies 

### ISSUE THREAD

**Issue by duarteocarmo** [DerwenAI/pytextrank#195]
When running the example from scratch - scipy is missing - you might want to add it to your `requirements.txt`

thanks for the great work!

**Comment by ceteri** [comment]
Yes, this appears to be an issue within NetworkX, based on their recent updates to prepare for the NetworkX 3.x release. This just started showing up in our CI builds.  I'm still trying to find a recommended resolution, since NetworkX gives a deprecation warning about how they plan to remove SciPy and `nx.pagerank_scipy()`

**Comment by ceteri** [comment]
PR #191 is attempting to resolve this; although I think we may have troubles later when `NetworkX` moves to 3.x ?
