### ISSUE TITLE
Is it possible to integrate Pytextrank with Flair NLP engine

### ISSUE THREAD

**Issue by coolcoder001** [DerwenAI/pytextrank#218]
Hi,

Is it possible to integrate PyTextRank with Flair NLP engine ?

**Comment by ceteri** [comment]
Hi @coolcoder001,

Some of this code could be reworked to support `flair` instead, since it provides PoS tagging.

However, most likely the predictive performance would not be quite as good as with `spaCy` since `flair` lacks _lemmatization_ – they are more focused on supporting large language models rather than NLP in general.

In general, `pytextrank` is built to be a pipeline extension for `spaCy` and this kind of architecture isn't provided in `flair`.
