### ISSUE TITLE
Running text rank using nlp.pipe

### ISSUE THREAD

**Issue by shashwath94** [DerwenAI/pytextrank#40]
So I add PyTR to the nlp pipeline as a component as shown in the example snippet but when I use like the following, the `doc._.phrases` contains the phrases for the last document always.

```
texts = [list of strings]
docs = list(nlp.pipe(texts))
doc_terms = []
for doc in docs:
        textrank_result = [p.text for p in doc._.phrases]
        doc_terms.append(textrank_result)
``` 
In the for loop, `doc_terms` is always the terms for the last doc object even though the doc objects are different. Any idea what I might be doing wrong here? Thanks.

**Comment by ceteri** [comment]
That may be due to PyTextRank being integrated into the spaCy pipeline as an *attribute extension*, while a *property extension* could perhaps resolve that? Will test it.

One workaround would be if you iterated over the texts instead of the docs? For example:

```
texts = [list of strings]
doc_terms = []

for text in texts:
    doc = nlp(text)
    textrank_result = [p.text for p in doc._.phrases]
    doc_terms.append(textrank_result)
```

That approach would consume less memory, unless there's a reason to keep the `docs` list for later use?

**Comment by shashwath94** [comment]
Yeah I ended up looping over the `texts` list. Also yes, I'm saving `p.rank` values as well. Thanks @ceteri for the help!

**Comment by de-code** [comment]
Iterating over `nlp.pipe` also seem to work:

```python
texts = ['This is a test', 'This is another example']
doc_terms = []
for doc in nlp.pipe(texts):
        textrank_result = [p.text for p in doc._.phrases]
        doc_terms.append(textrank_result)
print(doc_terms)
# >>> [['a test'], ['another example']]
```
