### ISSUE TITLE
Keyword extraction

### ISSUE THREAD

**Issue by danielp3011** [DerwenAI/pytextrank#43]
Hi there, I'm working on a project extracting keywords from a german text. Is there a tutorial on how to extract keywords using pytextrank?

Best regards,

**Comment by ceteri** [comment]
Hi @danielp3011, yes the [`example.py`](https://github.com/DerwenAI/pytextrank/blob/master/example.py) file shows source for extracting key phrases from a text. You'd need to configure `spaCy` with the German language modules described at <https://spacy.io/models/de>

**Comment by imeano** [comment]
Hello,

I'm trying to do keyword extraction of short texts in Portuguese. I would like to confirm more precisely what the spaCy configurations necessary to do this are since I'm not being able to get keywords from it.

I just loaded the `pt_core_news_sm` model instead of the English model and fed a Portuguese text in the example given in https://spacy.io/universe/project/spacy-pytextrank

The tagger in the Portuguese model has very different labels. The parser also seems to have a different set. Would that be a problem? Is there a way to work around it if it is? Am I missing something else entirely?

Thanks in advance

**Comment by ceteri** [comment]
Hi @imeano -

Let's figure out how to support that use case properly in PyTextRank.

Working with the `pt_core_news_sm` model, could you provide a notebook or GitHub gist that shows:

  * sample input text in Portuguese
  * the phrases that one would expect to be extracted

If there are any configuration changes needed, we'll make updates for that.

Many thanks -
Paco

**Comment by imeano** [comment]
Thanks for the kind and rapid response.

To give a bit more context, at this point I'm surveying different tools for the job and pytextrank seemed a good fit since I'm already using spaCy and the usage of lemma and verbs to build the graph seem like good ideas to me. I would also like it if verbs could optionally be included as keywords but that's not very important.

I tried testing code in English and a translation of the English text for Portuguese I've made myself. English output is great! Portuguese output seems to be empty like what has been described in issue #54. Here's the code I ran:
```
### Very close to example given in spacy.io page
### Some minor variable renaming to explicitly separate English and Portuguese

import pytextrank
import spacy

# load a spaCy model, depending on language, scale, etc.

en = spacy.load('en_core_web_sm')

# add PyTextRank into the spaCy pipeline

tr_en = pytextrank.TextRank(logger=None)
en.add_pipe(tr_en.PipelineComponent, name="textrank_en", last=True)

# parse the document

text_en = 'In which cases do I have to consider induction effects when designing eletronic circuit boards?'

doc_en = en(text_en)

print("en pipeline", en.pipe_names)
print("elapsed time: {} ms".format(tr_en.elapsed_time))

# examine the top-ranked phrases in the document

for phrase in doc_en._.phrases:
    print("{:.4f} {:5d}  {}".format(phrase.rank, phrase.count, phrase.text))
    print(phrase.chunks)

# load a spaCy model, depending on language, scale, etc.

pt = spacy.load("pt_core_news_sm")

# add PyTextRank into the spaCy pipeline

tr_pt = pytextrank.TextRank(logger=None)
pt.add_pipe(tr_pt.PipelineComponent, name="textrank_pt", last=True)

# parse the document

text_pt = 'Em que casos devo considerar efeitos indutivos ao desenhar placas de circuitos eletrônicos?'

doc_pt = pt(text_pt)

print("pt pipeline", pt.pipe_names)
print("elapsed time: {} ms".format(tr_pt.elapsed_time))

# examine the top-ranked phrases in the document

for phrase in doc_pt._.phrases:
    print("{:.4f} {:5d}  {}".format(phrase.rank, phrase.count, phrase.text))
    print(phrase.chunks)
```

I get the output:
```
en pipeline ['tagger', 'parser', 'ner', 'textrank_en']
elapsed time: 39.374589920043945 ms
0.2537     1  eletronic circuit boards
[eletronic circuit boards]
0.2333     1  induction effects
[induction effects]
0.0362     1  which cases
[which cases]
0.0000     1  i
[I]

pt pipeline ['tagger', 'parser', 'ner', 'textrank_pt']
elapsed time: 1.9516944885253906 ms
```

My expected Output is something like this:
```
pt pipeline ['tagger', 'parser', 'ner', 'textrank_pt']
elapsed time: xx.xxxxxxxxxxx ms
0.xxxx     1  circuitos eletronicos
[circuitos eletrônicos]
0.yyyy     1  efeitos indutivos
[efeitos indutivos]
0.0000     1  casos
[casos]
```
I wanted to create an example in which the translated expressions would be the expected output. But the languages are sufficiently different to be hard to find examples like that which are also relevant.

Anyhow, to reiterate, I think the outputs for the English language are great and I would like the Portuguese output to be much the same.

**Comment by imeano** [comment]
Oh, 2 other things:

1. In writing the above comment I had the idea that lemmas might actually be a problem. I haven't worked with `pt_core_news_sm` lemmas in a while, but I recall they were somewhat strange.
2. I would be willing to help with coding solutions for generalizing to other languages, not just Portuguese, this subject is very interesting to me. I don't much time available though. But, you know, keep in mind there is an open offer for slow moving help if you wish.

**Comment by imeano** [comment]
Hello again,

After giving more attention to issue #54 , I checked that noun_chunks were empty and tested adding a simple syntax iterator. So I was able to confirm it's basically the same issue. I guess I should move things to that issue, then.

**Comment by ceteri** [comment]
Many thanks @imeano and I'll work on this in #54
