### ISSUE TITLE
Can't use PyTextRank in parallel?

### ISSUE THREAD

**Issue by rjurney** [DerwenAI/pytextrank#61]
I am trying to summarize many documents and am having trouble improving performance because I can't figure out how to use the PyTextRank extension for document summarization in parallel among multiple processes. The only method for parallel processing listed in the [docs][1] shows the use of [`nlp.pipe()` (Language.pipe)][2]. However, you can't call PyTextRank on a document inside `nlp.pipe()`, it only allows itself to be used via [`Language.add_pipe()`][3]. I've looked at the [code for pytextrank.pytextrank][4] to verify this.

How do you use a Pipeline in parallel without using `nlp.pipe()`? How do you make `nlp.add_pipe()` parallel?

  [1]: https://spacy.io/usage/examples#multi-processing
  [2]: https://spacy.io/api/language#pipe
  [3]: https://pypi.org/project/pytextrank
  [4]: https://github.com/DerwenAI/pytextrank/blob/master/pytextrank/pytextrank.py

**Comment by ceteri** [comment]
That's a question for spaCy, about architecture. It's not clear why you need task parallelism, but again that's a matter of spaCy architecture. Recent work there leverages [Ray](https://ray.io/) for some of the compute-intensive parts.

In my experience with NLP work at scale, job parallelism is generally more useful, due to dependencies in the pipelined nature of this work.

That said, your question doesn't have much of any bearing on PyTextRank.

**Comment by rjurney** [comment]
@ceteri Your plugin could have a method that allows it to be used in `Language.pipe()`, which is the only documented method of parallelism in spaCy. It does not. How is that a spaCy issue?
