### ISSUE TITLE
How to work with large texts for phrase ranking?

### ISSUE THREAD

**Issue by sayak1711** [DerwenAI/pytextrank#66]
I want to rank phrases from many documents at once but spacy's 1 million character limit for nlp object is preventing me from to do so. Also if I set nlp.max_length to be higher then it stays stuck. What would be the efficient way to do this?

**Comment by ceteri** [comment]
Hi Sayak,

Generally the most efficient way to handle that is to iterate through the corpus, handling one document at a time.  If you want to parallelize, I highly recommend using [Ray](https://ray.io/) -- where it's super simple to parallelize that kind of pattern in Py.

If you need to aggregate the key phrase rankings out of many documents, then take the ranked phrases as a collection scale instead of the raw text input. That scales more effectively.  Also, if you ever need to collect lots of metrics or compare items at scale, some of the approximation algorithms in [datasketch](https://github.com/ekzhu/datasketch) are very helpful.
